### ISSUE TITLE
Offline standalone or firefox addon for jscalc?

### ISSUE THREAD

**Issue by potholiday** [ivan7237d/jscalc#71]
I am impressed by jscalc its fast and easy way to create our own custom calculator. But the biggest drawback which i found in jscalc is, it only works with internet. I am looking for an offline app because I am from that part of the world where I dont get internet 24/7 and also because of the cost of the internet I tends to use data frugally. Is there a way in which we can use already made online jscalc app as an offline app. Lets say as a standalone offline jscalc calculator or as an add-on(offline) in Firefox.

**Comment by ivan7237d** [comment]
Thanks for the feedback. Unfortunately what you described isn't possible in the current implementation of jscalc, although once you load the page with the calculator in the browser, the calculator would continue to function even if you lose connection.

**Comment by potholiday** [comment]
@ivan7237d  Thanks for the quick reply. The idea to load jscalc once in the browser is a good one but modern browsers are very much power hungry and leads to laptop overheating. Anyway thanks for creating this awesome product.

**Comment by ivan7237d** [comment]
Generally speaking offline capabilities would make sense, but it's a pretty small project, so unfortunately I don't think in the foreseeable future I'll have time available for this type of features.
