### ISSUE TITLE
Text input field

### ISSUE THREAD

**Issue by Godsmith** [ivan7237d/jscalc#74]
It would be useful to have a Text input field in addition to the existing Number/Checkbox etc. My personal use case is that I would like to extract the digits from a string of the form "111.222.333" and then do mathematical operations on the result. This is not currently possible, since the input will just return undefined.

**Comment by ivan7237d** [comment]
That makes sense, I've just added this feature, should get published in a minute or so.

**Comment by Godsmith** [comment]
Verified. That is what I call response time!
