### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by ty2903** [ivan7237d/jscalc#75]
Hi Ivan,

We recently had a discussion in youtube comments of the tutorial video about inputs altering other inputs. I tried to go back to the calculator I was developing today and I can no longer access it. 

I would have messaged you on youtube, but comments are suddenly disabled for your video as well. If you don't mind me asking, what is happening? I was about to release the calculator as part of a developers blog for a PC video game I am a developer for. I'd like to get the calculator I made back.. or at minimum the code I wrote for it.

Thanks,

**Comment by ivan7237d** [comment]
@ty2903 Hi there, yes, I just got a notification that it's down for some reason, let me investigate — some technical problem.

**Comment by ivan7237d** [comment]
@ty2903 I just restarted the Heroku server, and it went back up. I wonder what's causing this and how to troubleshoot it. Roughly a month ago this happened too — that time it went back up by itself after a couple of hours.

**Comment by ty2903** [comment]
@ivan7237d 
Thanks for the super quick fix! :)
