### ISSUE TITLE
Настройка содержимого и отображения заголовков Input и Output

### ISSUE THREAD

**Issue by mainefremov** [ivan7237d/jscalc#76]
1. Добавить в настройку калькулятора возможность заменять Input и Output на собственные значения.
2. Дать возможность спрятать их.

1. Add to setting the ability to replace Input and Output with own values.
2. Allow to hide them.

**Comment by ivan7237d** [comment]
@mainefremov А проясните немножко, что имеется в виду под №1? Насчет второго, сейчас есть такая функциональность: 
- если в объекте, который вы возвращаете, нет property соответствующего какому-то из outputs, то этот output  не будет показываться
- если в настройках инпута стоит галочка autohide, и этот инпут не используется скриптом, то инпут не будет показываться.

**Comment by mainefremov** [comment]
@ivan7237d Простите, не уточнил. Имею ввиду не input/output как объекты ввода-вывода, а сами заголовки "Inputs" и "Outputs" в верхней части калькулятора. Русскоязычному пользователю встроенной версии на сайте они или не нужны, или нужны, но локализованные.

**Comment by ivan7237d** [comment]
@mainefremov Действительно, это нужная функциональность, сейчас добавил, в установках калькулятора появился пункт "Localization".
