### ISSUE TITLE
Integration with API's such as Google Maps

### ISSUE THREAD

**Issue by albertpintoapp** [ivan7237d/jscalc#77]
Say I want to create a calculator where the user puts in two destinations (with Google Address Autocomplete), and the calculator tells you the distance between the two or reads traffic information between the two, etc.

This data can be used to calculate other items. Any way to do this?

**Comment by ivan7237d** [comment]
No, unfortunately not – this would require an asynchronous call to browser api, and only synchronous scripts are supported. Also in practice I think those developers who'd want to do something relatively complex like this would be better off just building the whole calculator on their own.

**Comment by albertpintoapp** [comment]
Thanks Ivan for your feedback :)
