### ISSUE TITLE
Add Text as Output

### ISSUE THREAD

**Issue by albertpintoapp** [ivan7237d/jscalc#78]
Is there a way to add text in the Output Fields? As an example, I've created this Assessment Calculator, and at the end, I want to give out the areas where the user needs to work on, in TEXT.

https://jscalc.io/calc/Sc5CzzBV2oOslbmi

How do I do that?

**Comment by ivan7237d** [comment]
You can add another output and return a string as value for this output, I think this should for your use-case.

**Comment by albertpintoapp** [comment]
Thank you Ivan :)
